### ISSUE TITLE
Proposal: Some ideas to improve the open source contribution

### ISSUE THREAD

**Issue by DieterReuter** [kitematic/kitematic#282]
When you're publishing such a great project to the public, one of then main thing every maintainer want to get is: feedback.  Feedback, new ideas about improvements, bug fixes, and a lot of really cool features. 

**Proposals:**
I'd like to propose some minor changes and enhancements, just to get more and even better feedback.

1. Use a `AUTHORS` file ([example](https://github.com/syncthing/syncthing/blob/master/AUTHORS)) to document all the contributors to the project. This is not only for copyright purposes, but everbody who has contributed a PR or an idea will be proud to find his/her name on this list. And maybe you could also use a `NICKS` list too ([example](https://github.com/syncthing/syncthing/blob/master/NICKS)).

2. Create a new label `proposal` for proposing new features or architectural changes that needs to be discussed in detail, before you can decide whether to implement and how. I would greatly encourage everybody to use a `proposal` when the new wanted feature or enhancement isn't part of the current roadmap. And if this is so important or great for lots of users or use case, you can decide to put in on the roadmap earlier that planned.

3. The [ROADMAP.md](https://github.com/kitematic/kitematic/blob/master/ROADMAP.md) is really cool, but I think it could be even better, if you define more smaller work items. Then it should be easier to get help from the community. And maybe you could use it together as a check list, to show if a feature or work item is already done. 
Here is a small example (this contents is just random):

**Milestone 1**

* Awesome feature
  - [x] get a basic prototype working
  - [x] gather feedback from contributors
  - [ ] task A
  - [ ] task B
  - [ ] work done, ready for release

* Another hot feature
  - [ ] refactor the usage of `docker-machine` to use different types of machines
    - [ ] make it optional to download/install Oracle VM VirtualBox
  - [ ] implement a list of `Docker Host's` (aka machines)
    - [ ] new UI elements to display a list of Docker Hosts
    - [ ] grouping Containers running on the same Docker Hosts
  - [ ] use Kitematic as a UI front end for `docker-machine`
    - [ ] create a new machine
    - [ ] delete a machine
    - [ ] list all available machine

**Milestone 2**

* Microsoft Windows port
  - [ ] getting the main program running on Microsoft Windows
  - [ ] create basic installer for Microsoft Windows
  - [ ] add support for local hypervisors
    - [ ] support for Microsoft Hyper-V 
    - [ ] support for Oracle VM VirtualBox
    - [ ] support for VMware Workstation
  - [ ] add support for data center hypervisors
    - [ ] support for VMware vSphere
    - [ ] support for VMware vCloud

I think there are a lot more such small improvements we could define. This is a proposal and should be discussed and is therefor subject of change. Please feel free to improve and to get into more details.

**Comment by robtec** [comment]
:+1:

**Comment by Elesant** [comment]
Thanks @DieterReuter this is a really good idea :+1:

**Comment by jeffdm** [comment]
This is fantastic. 

1. Strongly agree. Contributors should be displayed openly. There's probably some sort of script we can use here.
2. This is key and a great idea. We can add this to CONTRIBUTING.md
3. +1 I think in general that it's hard for a new contributor to start helping with Kitematic right now. Having direct issues linked to our roadmap as a checklist would help people know what can be worked on that's priority.

Some next steps:
- [ ] Add an AUTHORS file or similar to show everyone who has contributed code. Find / create a script to regenerate the authors file from Git or the GitHub api.
- [ ] Change CONTRIBUTING.md to have proposal info
- [ ] Update ROADMAP.md to have checkboxes linked to priority GitHub issues
